<?php
     namespace App\Tests;

     use PHPUnit\Framework\TestCase;

     class DatabaseDependantTestCase extends TestCase
     {
         protected $entityManager;
         protected function setUp(): void
         {
             parent::setUp(); // TODO: Change the autogenerated stub

             require 'bootstrap-test.php';
             $this->entityManager = $entityManager;

             SchemaLoader::load($this->entityManager);
         }

         protected function tearDown(): void
         {
             parent::tearDown(); // TODO: Change the autogenerated stub
             $this->entityManager->close();
             $this->entityManager = null;
         }

         public function assertDatabaseHas(string $entity, array $criteria)
         {
             $result = $this->entityManager->getRepository($entity)->findOneBy($criteria);

             $keyValuesString = $this->asKeyValuesString($criteria);
             $failureMessage = "A $entity record could not be found with the " .
                 "following attributes: {$keyValuesString} ";
             $this->assertTrue((bool) $result, $failureMessage);
         }

         public function asKeyValuesString(array $criteria, $separator = ' = ')
         {
             $mappedAttributes = array_map(function($key, $value) use ($separator) {
                 return $key . $separator . $value;
             }, array_keys($criteria), $criteria);
             return implode(',', $mappedAttributes);
         }
     }